/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tp2;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Byebay
 */
public class Card extends javax.swing.JPanel {
    private final int idmember;
    private final String kodeGroup;
    private final dbConnection db;
    private JPanelCard home;
    /**
     * Creates new form Card
     * @param id
     * @param nama
     * @param role
     * @param usia
     * @param foto
     * @param kodeGroup
     * @param home
     */
    public Card(int id, String nama, String role, int usia, String foto, String kodeGroup, JPanelCard home) {
        initComponents();
        // db connection
        db = new dbConnection();
        // inisialisasi private variabel 
        this.idmember = id;
        this.kodeGroup = kodeGroup;
        this.home = home;
        //
        String tempId = Integer.toString(id);
        String tempUsia = Integer.toString(usia);
        idMember.setText(tempId);
        namaMember.setText(nama);
        roleMember.setText(role);
        usiaMember.setText(tempUsia);
        //display foto
        BufferedImage fileImg = null;
        File img = new File("src/tp2/images/" + foto);
        try {
            fileImg = ImageIO.read(img);
            int width = fotoMember.getWidth(), height = fotoMember.getHeight();
            if(width == 0){
                width = 115;
            }
            if(height == 0){
                height = 139;
            }
            Image image = fileImg.getScaledInstance(width, height,Image.SCALE_SMOOTH);
            ImageIcon ic = new ImageIcon(image);
            fotoMember.setIcon(ic);
        } catch (IOException ex) {
            Logger.getLogger(JPanelCard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void deleteData(){
        int response = JOptionPane.showConfirmDialog(this, "Data akan di delete!", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
          if(response == JOptionPane.YES_OPTION){
              String sql = "DELETE FROM member WHERE ID_MEMBER = '"+idmember+"'";
              db.updateQuery(sql);
              // home
              this.home.setPanel();
              // Show Information
              // ...
              System.out.println("Delete Success!");
              JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
          }
    }
    
    public void updateData(){
        ResultSet res = db.selectQuery("SELECT * FROM member WHERE ID_MEMBER = '" + idmember + "'");
        try{
            if(res.next()){
                String nama, role, kode;
                int usia, id;
                // get data
                id = res.getInt(1);
                kode = res.getString(2);
                nama = res.getString(3);
                role = res.getString(4);
                usia = res.getInt(5);
                // pass ke objek member
                Member mem = new Member(id, nama, role, usia, this.home);
                mem.setVisible(true);
            }
        }catch (SQLException ex) {
              System.out.println(ex.getMessage());
          }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        MainCard = new javax.swing.JPanel();
        member = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        namaMember = new javax.swing.JLabel();
        roleMember = new javax.swing.JLabel();
        usiaMember = new javax.swing.JLabel();
        idMember = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        fotoMember = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        MainCard.setBackground(new java.awt.Color(255, 255, 255));
        MainCard.setForeground(new java.awt.Color(0, 0, 0));

        member.setBackground(new java.awt.Color(0, 0, 0));
        member.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        member.setForeground(new java.awt.Color(0, 0, 0));
        member.setText("Member");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nama :");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Role :");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Usia :");

        editButton.setBackground(new java.awt.Color(0, 51, 255));
        editButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 13)); // NOI18N
        editButton.setForeground(new java.awt.Color(255, 255, 255));
        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(255, 0, 51));
        deleteButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 13)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        namaMember.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        namaMember.setForeground(new java.awt.Color(0, 0, 0));
        namaMember.setText("nama member");

        roleMember.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        roleMember.setForeground(new java.awt.Color(0, 0, 0));
        roleMember.setText("role member");

        usiaMember.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        usiaMember.setForeground(new java.awt.Color(0, 0, 0));
        usiaMember.setText("usia member");

        idMember.setBackground(new java.awt.Color(0, 0, 0));
        idMember.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        idMember.setForeground(new java.awt.Color(0, 0, 0));
        idMember.setText("id");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fotoMember, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fotoMember, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MainCardLayout = new javax.swing.GroupLayout(MainCard);
        MainCard.setLayout(MainCardLayout);
        MainCardLayout.setHorizontalGroup(
            MainCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MainCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainCardLayout.createSequentialGroup()
                        .addGap(0, 79, Short.MAX_VALUE)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainCardLayout.createSequentialGroup()
                        .addGroup(MainCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainCardLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(namaMember))
                            .addGroup(MainCardLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roleMember))
                            .addGroup(MainCardLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usiaMember))
                            .addGroup(MainCardLayout.createSequentialGroup()
                                .addComponent(member)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idMember)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        MainCardLayout.setVerticalGroup(
            MainCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainCardLayout.createSequentialGroup()
                .addGroup(MainCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MainCardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MainCardLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(MainCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(member)
                            .addComponent(idMember))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MainCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(namaMember))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MainCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(roleMember))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MainCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(usiaMember))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MainCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("delete data " + idmember);
        deleteData();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("update data");
//        this.home.dispose();
        updateData();
    }//GEN-LAST:event_editButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainCard;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel fotoMember;
    private javax.swing.JLabel idMember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel member;
    private javax.swing.JLabel namaMember;
    private javax.swing.JLabel roleMember;
    private javax.swing.JLabel usiaMember;
    // End of variables declaration//GEN-END:variables
}
